yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(),
         name='author'),
    path('tech/', views.AboutTechView.as_view(),
         name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('create/', views.post_create, name='post_create'),
    path("posts/<int:post_id>/edit/", views.post_edit, name='post_edit'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/', views.profile_follow,
         name='profile_follow'
         ),
    path('profile/<str:username>/unfollow/', views.profile_unfollow,
         name='profile_unfollow'
         ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

yatube/posts/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models

from core.models import CreatedModel

User = get_user_model()


class Group(models.Model):
    """Модель для создания таблицы Group."""

    title = models.CharField(verbose_name='Название поста',
                             max_length=200)
    slug = models.SlugField(verbose_name='url адрес',
                            max_length=200, unique=True)
    description = models.TextField(verbose_name="Описание группы")

    class Meta:
        verbose_name = 'группа'
        verbose_name_plural = 'группы'

    def __str__(self):
        return self.title


class Post(CreatedModel):
    """Модель для создания таблицы Post."""

    text = models.TextField(verbose_name="Содержание поста")
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name="Автор поста",
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name="Название группы",
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        null=True,
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'пост'
        verbose_name_plural = 'посты'

    def __str__(self):
        return self.text[:settings.CHAR_NUMBER_FOR_ADMIN]


class Comment(CreatedModel):
    """Модель для создания комментариев к постам."""

    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Откоменнтированный пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария'
    )
    text = models.TextField(
        verbose_name='Комментарий'
    )

    def __str__(self):
        return self.text

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'комментарий'
        verbose_name_plural = 'комментарии'


class Follow(models.Model):
    """Модель для подписок на авторов."""

    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             related_name="follower",
                             verbose_name='Подписчик')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name="following",
                               verbose_name='Автор, на которого подписались')

    class Meta:
        verbose_name = 'подписка'
        verbose_name_plural = 'подписки'

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args,
                         **kwargs)
        self.fields['text'].widget.attrs['placeholder'] = (
            'Текст твой потребен, мы в ожидании, '
            'не тяни с этим 😏'
        )
        self.fields['group'].empty_label = (
            'Группа сама себя не выберет, действуй! 😎'
        )

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        help_texts = {
            'text': 'Пиши в поле выше.',
            'group': 'Нажми на текст выше и появится '
                     'список доступных групп.',
            'image': 'Загрузи картинку и будет счастье.'
        }


class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args,
                         **kwargs)
        self.fields['text'].widget.attrs['placeholder'] = (
            'Комментируй изо всех сил!'
        )

    class Meta:
        model = Comment
        fields = ('text',)
        help_texts = {'text': 'Текст комментария'}

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User
from .utils import paginator


def index(request):
    """
    Функция для вывода главной страницы
    и первых 10-ти постов из БД постранично.
    """
    post_list = Post.objects.select_related().all()
    page_obj = paginator(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    """
    Функция для вывода страниц сообщества и
    первых 10-ти постов из БД постранично.
    """
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.select_related().all()
    page_obj = paginator(request, post_list)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    """Функция для вывода всех постов пользователя."""
    author = get_object_or_404(User, username=username)
    post_list = author.posts.select_related().all()
    page_obj = paginator(request, post_list)
    following = (request.user != author
                 and request.user.is_authenticated
                 and Follow.objects.filter(user=request.user,
                                           author=author).exists())
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    """
    Функция для вывода информации об отдельном посте пользователя.
    """
    post = get_object_or_404(Post.objects.select_related(),
                             pk=post_id)
    form = CommentForm(request.POST or None)
    comments = post.comments.all()
    context = {'post': post,
               'comments': comments,
               'form': form,
               }
    return render(request,
                  'posts/post_detail.html',
                  context)


@login_required
def post_create(request):
    """
    Функция для создания нового поста,
    если пользователь зарегистрирован.
    """
    form = PostForm(request.POST or None,
                    files=request.FILES or None)
    if form.is_valid():
        new_post_create = form.save(commit=False)
        new_post_create.author = request.user
        form.save()
        return redirect('posts:profile',
                        username=request.user)
    context = {
        'form': form
    }
    return render(request,
                  'posts/create_post.html',
                  context)


@login_required
def post_edit(request, post_id):
    """
    Функция для редактирования поста новым пользователем.
    """
    post = get_object_or_404(Post.objects.select_related(),
                             pk=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail',
                        post_id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post,
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail',
                        post_id=post.id)
    context = {
        'form': form,
        'is_edit': True,
        'post': post,
    }
    return render(request,
                  'posts/create_post.html',
                  context)


@login_required
def add_comment(request, post_id):
    """Функция, дающая возможность оставлять комментарии."""
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        form.save()
    return redirect('posts:post_detail', post_id)


@login_required
def follow_index(request):
    """Отображение подписок."""
    post = Post.objects.filter(author__following__user=request.user)
    page_obj = paginator(request, post)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    """Подписаться на автора."""
    if username != request.user.username:
        author = get_object_or_404(User, username=username)
        Follow.objects.get_or_create(
            user=request.user,
            author=author,
        )
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    """Отписаться от автора."""
    author = get_object_or_404(User, username=username)
    follower = Follow.objects.filter(user=request.user, author=author)
    if follower.exists():
        follower.delete()
    return redirect('posts:profile', username)

yatube/templates/includes/error_handler_for_forms.html
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
</footer>

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-expand-sm navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
            aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse ms-3" id="navbarText">
      <ul class="nav nav-pills ms-auto top-menu">
        {% with request.resolver_match.view_name as view_name %}
        <li class="nav-item active">
          <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}"
             href="{% url 'about:author' %}">Об
            авторе</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}"
             href="{% url 'about:tech' %}">Технологии</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'posts:post_create' %}">Новая запись</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link link-light {% if view_name  == 'users:password_change_form' %}active{% endif %}"
             href="{% url 'users:password_change_form' %}">Изменить пароль</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link link-light {% if view_name  == 'users:logout' %}active{% endif %}"
             href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-dark" href="{% url 'posts:profile' user.username %}">Пользователь: {{ user.username }}</a>
        </li>
        {% else %}
        <li class="nav-item active">
          <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}"
             href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}"
             href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
        {% endwith %}
      </ul>
    </div>
  </div>
</nav>

yatube/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            Предыдущая
          </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            Следующая
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

yatube/templates/includes/posts.html
{% load thumbnail %}
  <article>
    <ul>
      {% if not author_page %}
      <li>
        Автор: <a href="{% url 'posts:profile' post.author.username %}">{{ post.author.get_full_name }}</a>
      </li>
      {% endif %}
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
      </ul>
        <p>{{ post.text|linebreaks }}</p>
          {% if post.group and not page_group %}
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a> <br>
          {% endif %}
        <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
  </article>

yatube/templates/includes/switcher.html
{% if user.is_authenticated %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a 
          class="nav-link {% if index %}active{% endif %}"
          href="{% url 'posts:index' %}"
        >
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a 
           class="nav-link {% if follow %}active{% endif %}"
           href="{% url 'posts:follow_index' %}"
        >
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %}

yatube/templates/includes/tags_form.html
{% load user_filters %}
{% csrf_token %}
{% for field in form %}
  <div class="form-group row my-3"
      {% if field.field.required %}
       aria-required="true"
      {% else %}
       aria-required="false"
      {% endif %}>
    <label for="{{ field.id_for_label }}">
      {{ field.label }}
      {% if field.field.required %}
        <span class="required text-danger">*</span>
      {% endif %}
    </label>
    <div>
      {{ field|addclass:'form-control' }}
      {% if field.help_text %}
        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
          {{ field.help_text|safe }}
        </small>
      {% endif %}
    </div>
  </div>
{% endfor %}