yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(),
         name='author'),
    path('tech/', views.AboutTechView.as_view(),
         name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('create/', views.post_create, name='post_create'),
    path("posts/<int:post_id>/edit/", views.post_edit, name='post_edit'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/', views.profile_follow,
         name='profile_follow'
         ),
    path('profile/<str:username>/unfollow/', views.profile_unfollow,
         name='profile_unfollow'
         ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

yatube/posts/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models

from core.models import CreatedModel

User = get_user_model()


class Group(models.Model):
    """Модель для создания таблицы Group."""

    title = models.CharField(verbose_name='Название поста',
                             max_length=200)
    slug = models.SlugField(verbose_name='url адрес',
                            max_length=200, unique=True)
    description = models.TextField(verbose_name="Описание группы")

    class Meta:
        verbose_name = 'группа'
        verbose_name_plural = 'группы'

    def __str__(self):
        return self.title


class Post(CreatedModel):
    """Модель для создания таблицы Post."""

    text = models.TextField(verbose_name="Содержание поста")
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name="Автор поста",
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name="Название группы",
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        null=True,
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'пост'
        verbose_name_plural = 'посты'

    def __str__(self):
        return self.text[:settings.CHAR_NUMBER_FOR_ADMIN]


class Comment(CreatedModel):
    """Модель для создания комментариев к постам."""

    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Откоменнтированный пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария'
    )
    text = models.TextField(
        verbose_name='Комментарий'
    )

    def __str__(self):
        return self.text

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'комментарий'
        verbose_name_plural = 'комментарии'


class Follow(models.Model):
    """Модель для подписок на авторов."""

    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             related_name="follower",
                             verbose_name='Подписчик')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name="following",
                               verbose_name='Автор, на которого подписались')

    class Meta:
        verbose_name = 'подписка'
        verbose_name_plural = 'подписки'

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args,
                         **kwargs)
        self.fields['text'].widget.attrs['placeholder'] = (
            'Текст твой потребен, мы в ожидании, '
            'не тяни с этим 😏'
        )
        self.fields['group'].empty_label = (
            'Группа сама себя не выберет, действуй! 😎'
        )

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        help_texts = {
            'text': 'Пиши в поле выше.',
            'group': 'Нажми на текст выше и появится '
                     'список доступных групп.',
            'image': 'Загрузи картинку и будет счастье.'
        }


class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args,
                         **kwargs)
        self.fields['text'].widget.attrs['placeholder'] = (
            'Комментируй изо всех сил!'
        )

    class Meta:
        model = Comment
        fields = ('text',)
        help_texts = {'text': 'Текст комментария'}

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User
from .utils import paginator


def index(request):
    """
    Функция для вывода главной страницы
    и первых 10-ти постов из БД постранично.
    """
    post_list = Post.objects.select_related().all()
    page_obj = paginator(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    """
    Функция для вывода страниц сообщества и
    первых 10-ти постов из БД постранично.
    """
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.select_related().all()
    page_obj = paginator(request, post_list)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    """Функция для вывода всех постов пользователя."""
    author = get_object_or_404(User, username=username)
    post_list = author.posts.select_related().all()
    page_obj = paginator(request, post_list)
    following = (request.user != author
                 and request.user.is_authenticated
                 and Follow.objects.filter(user=request.user,
                                           author=author).exists())
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    """
    Функция для вывода информации об отдельном посте пользователя.
    """
    post = get_object_or_404(Post.objects.select_related(),
                             pk=post_id)
    form = CommentForm(request.POST or None)
    comments = post.comments.all()
    context = {'post': post,
               'comments': comments,
               'form': form,
               }
    return render(request,
                  'posts/post_detail.html',
                  context)


@login_required
def post_create(request):
    """
    Функция для создания нового поста,
    если пользователь зарегистрирован.
    """
    form = PostForm(request.POST or None,
                    files=request.FILES or None)
    if form.is_valid():
        new_post_create = form.save(commit=False)
        new_post_create.author = request.user
        form.save()
        return redirect('posts:profile',
                        username=request.user)
    context = {
        'form': form
    }
    return render(request,
                  'posts/create_post.html',
                  context)


@login_required
def post_edit(request, post_id):
    """
    Функция для редактирования поста новым пользователем.
    """
    post = get_object_or_404(Post.objects.select_related(),
                             pk=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail',
                        post_id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post,
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail',
                        post_id=post.id)
    context = {
        'form': form,
        'is_edit': True,
        'post': post,
    }
    return render(request,
                  'posts/create_post.html',
                  context)


@login_required
def add_comment(request, post_id):
    """Функция, дающая возможность оставлять комментарии."""
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        form.save()
    return redirect('posts:post_detail', post_id)


@login_required
def follow_index(request):
    """Отображение подписок."""
    post = Post.objects.filter(author__following__user=request.user)
    page_obj = paginator(request, post)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    """Подписаться на автора."""
    if username != request.user.username:
        author = get_object_or_404(User, username=username)
        Follow.objects.get_or_create(
            user=request.user,
            author=author,
        )
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    """Отписаться от автора."""
    author = get_object_or_404(User, username=username)
    follower = Follow.objects.filter(user=request.user, author=author)
    if follower.exists():
        follower.delete()
    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
{% if is_edit %} Редактирование поста {% else %} Новый пост {% endif %}
{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}
          Редактировать запись
          {% else %}
          Добавить запись
          {% endif %}
        </div>
        <div class="card-body">
          {% include 'includes/error_handler_for_forms.html' %}
          <form
              action="{% if is_edit %}{% url 'posts:post_edit' post.id %}{% else %}{% url 'posts:post_create' %}{% endif %}"
              method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'includes/tags_form.html' %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                Сохранить
                {% else %}
                Добавить
                {% endif %}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %} Подписки {% endblock %}
{% block content %}
{% include 'includes/switcher.html' with follow=True %}
  {% for post in page_obj %}
    {% include 'includes/posts.html' %}
    {% if not forloop.last %}
      <hr>{% endif %}
  {% endfor %}
  {% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %} Записи сообщества {{ group.title }} {% endblock %}
{% block content %}
  <h1>{{ group.title }}</h1>
  <p>{{ group.description|linebreaks }}</p>
  {% for post in page_obj %}
    {% include 'includes/posts.html' with page_group=True %}
    {% if not forloop.last %}
      <hr> {% endif %}
  {% endfor %}
  {% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load cache %}
{% block title %} Последние обновления на сайте {% endblock %}
{% block content %}
{% include 'includes/switcher.html' with index=True %}
{% cache 20 index_page with page_obj %}
  {% for post in page_obj %}
    {% include 'includes/posts.html' %}
    {% if not forloop.last %}
      <hr>{% endif %}
  {% endfor %}
{% endcache %}
  {% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}
{% block title %} Пост {{ post.text|slice:":30" }}{% endblock %}
{% block content %}
<div class="row">
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
      {% if post.group %}
      <li class="list-group-item">
        Группа: {{ post.group.title }}
        <br>
        <a href="{% url 'posts:group_list' post.group.slug %}">
          все записи группы
        </a>
        {% endif %}
      </li>
      <li class="list-group-item">
        Автор: {{ post.author.get_full_name }}
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Всего постов автора: <span>{{ post.author.posts.count }}</span>
      </li>
      <li class="list-group-item">
        <a href="{% url 'posts:profile' post.author %}">
          все посты пользователя
        </a>
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>
      {{ post.text|linebreaks }}
    </p>
    {% if post.author.get_full_name == user.get_full_name %}
    <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
      редактировать запись
    </a>
    {% endif %}
  </article>
  {% if user.is_authenticated %}
    <div class="card my-4">
      <h5 class="card-header">Добавить комментарий:</h5>
      <div class="card-body">
        <form method="post" action="{% url 'posts:add_comment' post.id %}">
            {% csrf_token %}
          <div class="form-group mb-2">
            {{ form.text|addclass:"form-control" }}
           </div>
          <button type="submit" class="btn btn-primary">Отправить</button>
        </form>
      </div>
    </div>
  {% endif %}
  {% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
      <p>
        {{ comment.text }}
      </p>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %} Профайл пользователя {{ author.get_full_name }} {% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>Все посты пользователя {{ author.get_full_name }} </h1>
    <h3>Всего постов: {{ author.posts.count }} </h3>
    {% if user != author %}
      {% if following %}
    <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >
      Отписаться
    </a>
      {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >
        Подписаться
      </a>
      {% endif %}
    {% endif %}
   {% for post in page_obj %}
      {% include 'includes/posts.html' with author_page=True %}
      {% if not forloop.last %}
        <hr>{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}