yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(),
         name='author'),
    path('tech/', views.AboutTechView.as_view(),
         name='tech'),
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view
        (template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view
        (template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view
        (template_name='users/password_change_form.html'),
        name='password_change_form'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view
        (template_name='users/password_change_done.html'),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view
        (template_name='users/password_reset_form.html'),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view
        (template_name='users/password_reset_done.html'),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view
        (template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view
        (template_name='users/password_reset_complete.html'),
        name='password_reset_complete'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

yatube/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %} Вы вышли из системы {% endblock %}
{% block content %}
  {% with card_header='Выход' card_body='Вы вышли из своей учётной записи. Ждём вас снова!' %}
    {% include 'users/includes/card.html' %}
  {% endwith %}
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
  {% with card_header='Выход' form_tag=True %}
  {% include 'users/includes/card.html' with button='Войти' a_text='Забыли пароль?' a_access='login' %}
  {% endwith %}
{% endblock %}

yatube/templates/users/password_change_done.html
{% extends "base.html" %}
{% block title %}Пароль изменён{% endblock %}
{% block content %}
    {% with card_header='Пароль изменён' card_body='Пароль изменён успешно' %}
      {% include 'users/includes/card.html' %}
    {% endwith %}
{% endblock %}

yatube/templates/users/password_change_form.html
{% extends "base.html" %}
{% block title %}Изменение пароля{% endblock %}
{% block content %}
  {% with card_header='Изменить пароль' form_tag=True %}
  {% include 'users/includes/card.html' with button='Изменить пароль' %}
  {% endwith %}
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block content %}
<div class="container py-5">
  {% with card_header='Восстановление пароля завершено' %}
  {% include 'users/includes/card.html' with card_body='Ваш пароль был сохранен. Используйте его для входа' user_password=True%}
  {% endwith %}
</div>
{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Новый пароль{% endblock %}
{% block content %}
  {% if validlink %}
    {% with card_header='Введите новый пароль' form_tag=True %}
    {% include 'users/includes/card.html' with button='Назначить новый пароль' %}
    {% endwith %}
  {% else %}
    {% with card_header='Ошибка' card_body='Ссылка сброса пароля содержит ошибку или устарела.' %}
    {% include 'users/includes/card.html' %}
    {% endwith %}
  {% endif %}
{% endblock %}

yatube/templates/users/password_reset_done.html
{% extends "base.html" %}
{% block title %}Новый пароль{% endblock %}
{% block content %}
  {% with card_header='Отправлено письмо' card_body='Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля' %}
    {% include 'users/includes/card.html' %}
  {% endwith %}
{% endblock %}

yatube/templates/users/password_reset_form.html
{% extends "base.html" %}
{% block title %}Сборс пароля{% endblock %}
{% block content %}
  {% load user_filters %}
  <div class="container py-5">
  {% with card_header='Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались' form_tag=True %}
  {% include 'users/includes/card.html' with button='Сбросить пароль' %}
  {% endwith %}
  </div>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Зарегистрироваться</div>
      <div class="card-body">
        {% load user_filters %}
        {% include 'includes/error_handler_for_forms.html' %}
        <form method="post" action="{% url 'users:signup' %}">
          {% csrf_token %}
          {% for field in form %}
          <div class="form-group row my-3">
            <label for="{{ field.id_for_label }}">
              {{ field.label }}
              {% if field.field.required %}
              <span class="required text-danger">*</span>
              {% endif %}
            </label>
            {{ field|addclass:'form-control' }}
            {% if field.help_text %}
            <small
                id="{{ field.id_for_label }}-help"
                class="form-text text-muted">
              {{ field.help_text|safe }}
            </small>
            {% endif %}
          </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Зарегистрироваться
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}